### ISSUE TITLE
Documentation issue

### ISSUE THREAD

**Issue by yaroze** [daco-tech/elasticman#2]
According to the documentation, the project is to be build by just running "make" with no arguments. However this doesn't generate any binaries.

Also, when running with --config, the following is what I get (but the file exists):
```
[pedro@firestarter elasticman]$ ./main clusterInfo   --config $PWD/config.json
   ____ __           __   _       __  ___       
  / __// /___ _ ___ / /_ (_)____ /  |/  /___ _ ___ 
 / _/ / // _ `/(_-</ __// // __// /|_/ // _ \`/ _ \
/___//_/ \_,_//___/\__//_/ \__//_/  /_/ \_,_//_//_/

2020/06/03 --> Loading Configs from /home/pedro/go/src/elasticman/config.json...
2020/06/03 No configuration file found. Looking for '/home/pedro/go/src/elasticman/config.json'.
[pedro@firestarter elasticman]$
```

**Comment by daco-tech** [comment]
First: 
According to the documentation, the project is to be build by just running "make" with no arguments. However this doesn't generate any binaries.

Fixed and documentation was updated.

**Comment by daco-tech** [comment]
Regarding the second question, the error message was wrong, and now it is fixed! :)

Probably you have a not well formated JSON config file, and now, with this fix you should be able to find whats wrong with your file.

Thank you for reporting this issue!

**Comment by yaroze** [comment]
Glad it was useful! :)
